project:
  type: website

website:
  title: "DOA journal occupational"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - R/OH_publications_analysis.qmd
      - abstract_EPICOH.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



